version: "3.0"
services:
  web:
    image: sakshikakkar121291/node-web-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_NAME=orderOnWheels
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123123123
    # entrypoint: ["/bin/bash", "cd /usr/src/app", "./start.sh"]
    command: /usr/src/app/start.sh && exec docker-entrypoint.sh node server.js
    depends_on:
      - db
  db:
    container_name: orderonwheels_db
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123123
      - MYSQL_DATABASE=orderOnWheels
      - MYSQL_ROOT_HOST=%